[tools]
go = "1.26.0"
"go:golang.org/x/tools/gopls" = "0.21.0"

[tasks."codegen:linux-amd64"]
env = {
  TARGET_GOOS = "linux",
  TARGET_GOARCH = "amd64"
}
run = "go run ./cmd/codegen"

[tasks."codegen:linux-arm64"]
env = {
  TARGET_GOOS = "linux",
  TARGET_GOARCH = "arm64"
}
run = "go run ./cmd/codegen"

[tasks.codegen]
depends = ["codegen:*"]
